"""updated patient records

Revision ID: 2f61e85511cb
Revises: fcf2ee6b66cf
Create Date: 2022-08-01 21:04:48.697310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f61e85511cb'
down_revision = 'fcf2ee6b66cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis', 'status')
    # ### end Alembic commands ###
