"""add score on test_images table

Revision ID: aac769d02624
Revises: 8c1cc76813bb
Create Date: 2022-08-09 18:10:13.608455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac769d02624'
down_revision = '8c1cc76813bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_images', sa.Column('scores', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_images', 'scores')
    # ### end Alembic commands ###
